### ISSUE TITLE
dummysoftware.com www.dummysoftware.com

### ISSUE THREAD

**Issue by p1r473** [hemiipatu/PiHoleBlocklists#12]
URL you wish to be removed:
dummysoftware.com www.dummysoftware.com

Why you believe this to be a false positive:
This is the website of a Chrome extension developer. They are not malicious softwares,
@hemiipatu

**Comment by hemiipatu** [comment]
For all intensive purposes _www.dummysoftware.com_ has been included in the blocklists as a precautionary measure due to some of the software/extensions being reported as malicious by multiple sources.

Further research into the aforementioned claims have previously been conducted and a code dump of the extension [easy auto refresh](https://chrome.google.com/webstore/detail/easy-auto-refresh/aabcgdmkeabbnleenpncegpcngjpnjkc?hl=en) can be found [here](https://pastebin.com/z9TQqGCZ) which shows logic used for data collection - something which the developer/publisher states would not be done as per the privacy section on the chrome extension store.

For the aforementioned reason alone this site and all its' contents cannot be trusted.

If you believe otherwise, you can add the site to your whitelist by either:

1. Go to your dashboard > Whitelist > Add the website to whitelist.
2. Via Terminal/Console > `pihole -w www.dummysoftware.com`
